defaults:
  - override hydra/launcher: submitit_slurm 

hydra:
  launcher:
    # submitit_folder: /checkpoint/${USER}/mc_runs/
    # queue: xeon
    tasks_per_node: 1
    cpus_per_task: 1
    gpus_per_node: 1
    timeout_min: 240
    mem_gb: 10
    # partition: dev
    # constraint: volta32gb
    # Change to your email
    # slurm_additional_parameters: ["--signal=USR1@120", "--cpus-per-task=10", "--mem=10G", "--mail-type=ALL", "--mail-user=your_email"]

exp_name: 0
save_dir: None
device: cuda

data:
  dataset: ImsVoxelsDataset
  # dataset: CoordsVoxelsDataset
  num_samples: 7000
  data_dir: data
  pct_train: 0.8
  pct_val: 0.1
  pct_test: 0.1

train:
  load: true
  lr: 0.0001
  num_updates: 50000
  eval_interval: 100
  log_interval: 1
  save_interval: 100
  batch_size: 32

model:
  name: ConvDenseDeconv
  # name: ConvDense
  # name: Dense
  # name: DenseDeconv

optimizer:

evaluate:
  val: False
  batch_size: 10